name: LetsStretch
options:
  bundleIdPrefix: com.lucasprim
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "26.2"
  generateEmptyDirectories: true
settings:
  base:
    SWIFT_VERSION: "6.0"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
packages:
  SwiftLintPlugins:
    url: https://github.com/SimplyDanny/SwiftLintPlugins
    from: "0.57.0"
targets:
  LetsStretch:
    type: application
    platform: macOS
    sources:
      - path: LetsStretch/Sources
      - path: LetsStretch/Resources/Assets.xcassets
      - path: LetsStretch/Resources/stretches.json
        type: file
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lucasprim.LetsStretch
        PRODUCT_NAME: LetsStretch
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_KEY_LSUIElement: true
        INFOPLIST_KEY_CFBundleDisplayName: "Let's Stretch"
        INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright \u00A9 2026 Lucas Prim. All rights reserved."
        GENERATE_INFOPLIST_FILE: true
        CODE_SIGN_ENTITLEMENTS: LetsStretch/Resources/LetsStretch.entitlements
        SWIFT_STRICT_CONCURRENCY: complete
    entitlements:
      path: LetsStretch/Resources/LetsStretch.entitlements
    postBuildScripts:
      - name: SwiftLint
        basedOnDependencyAnalysis: false
        script: |
          if command -v swiftlint >/dev/null 2>&1; then
            swiftlint lint --config "${SRCROOT}/.swiftlint.yml" "${SRCROOT}/LetsStretch/Sources"
          else
            echo "warning: SwiftLint not installed. Install via: brew install swiftlint"
          fi
  LetsStretchTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: LetsStretchTests/Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lucasprim.LetsStretchTests
        GENERATE_INFOPLIST_FILE: true
    dependencies:
      - target: LetsStretch
